export const facebook = "https://svgshare.com/i/9WV.svg"
export const instagram = "https://svgshare.com/i/9XV.svg"
export const iphone = "https://svgshare.com/i/9XU.svg"
export const arrow_left = "https://svgshare.com/i/9VE.svg" 
export const youtube = "https://svgshare.com/i/9VD.svg"